version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/build  #저장 위치

permissions:
  - object: /home/ec2-user/build
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root