# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: #이벤트를 감지하며 워크플로우를 실행시키는 조건
  push:
    branches: [ master ] #master 브렌치로 push할 때 실행
  pull_request:
    branches: [ master ]
  workflow_dispatch: #수동 시작

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $
        aws-secret-access-key: $
        aws-region: $
        
    - name: Upload to S3
      run: aws s3 cp --region us-east-2 ./$GITHUB_SHA.zip s3://checkin-deploy/$PROJECT_NAME/$GITHUB_SHA.zip

    - name: Code Deploy
      run: aws deploy create-deployment --application-name checkinApp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=checkin-deploy,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
